<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFFf8sQl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFFf8sQl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFFf8sQl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFFf8sQl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFFf8sQl\App_KernelDevDebugContainer([
    'container.build_hash' => 'FFf8sQl',
    'container.build_id' => '7052b327',
    'container.build_time' => 1680195623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFFf8sQl');
