<?php

namespace ContainerNmVmxUb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodoPostProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\TodoPostProcessor' shared autowired service.
     *
     * @return \App\State\TodoPostProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/TodoPostProcessor.php';

        return $container->privates['App\\State\\TodoPostProcessor'] = new \App\State\TodoPostProcessor(($container->privates['App\\Repository\\TodoRepository'] ?? $container->load('getTodoRepositoryService')));
    }
}
