<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhNyOxB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhNyOxB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIhNyOxB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIhNyOxB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIhNyOxB\App_KernelDevDebugContainer([
    'container.build_hash' => 'IhNyOxB',
    'container.build_id' => '74851bb6',
    'container.build_time' => 1680286472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhNyOxB');
