name: Node.js CI

on:
  push:
    branches: [ "node/express" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: SSH Remote Commandsx
      uses: appleboy/ssh-action@v0.1.8
      with:
        # ssh host
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_KEY }}
        script: whoami
